#!/usr/bin/env bash
# Script to install nginx and automatize some functions
apt-get update
apt-get -y upgrade
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
service nginx restart
