#!/usr/bin/env bash
# This script displays  numbers from 1 to 100
# displays FizzBuzz when the number is a multiple of 3 and 5
# displays Buzz when the number is multiple by 5
# displays Fizz when the number is a multiple of 3
# otherwise display the number in a list formart

i=1
while [ $i -le 100 ]
do
  
  if (( i % 5 == 0 )) && (( i % 3 == 0 )); then
    echo "FizzBuzz"

  elif (( i % 5 == 0 )); then
    echo "Buzz"
  
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  
  else
    echo $i
  fi
  ((i++))
done
